### ISSUE TITLE
how to create a sticky footer

### ISSUE THREAD

**Issue by blade-sensei** [blade-sensei/learning#33]

**Comment by blade-sensei** [comment]
implementing or blog website
deploy to server

**Comment by blade-sensei** [comment]
```css
html {
    position: relative;
    min-height: 100%;
}
body {
    margin: 0 0 100px; /* bottom = footer height */
}
#bottom-footer {
    position: absolute;
    left: 0;
    bottom: 0;
    height: 100px;
    width: 100%;
}
```

Solution

**Comment by blade-sensei** [comment]
we can also use 
```css
html {
height: 100vh
}
```

to adapt all the body/html content to fit in the viewport
