### ISSUE TITLE
vertical align testing css

### ISSUE THREAD

**Issue by blade-sensei** [blade-sensei/learning#56]

**Comment by blade-sensei** [comment]
```css
.parent {
    height: 200px;
    width: 200px;
    background-color: aqua;
    display: table-cell;
    vertical-align: middle;
}

.child {
    height: 60px;
    width: 60px;
    background-color: rgb(115, 255, 0);
    display: block;
    margin: 0 auto;
}
```
